# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PsLKX2PTI596gby7UzNmlK3VDOHUtVq

# 데이터 전처리
"""

import pandas as pd
import numpy as np

df = pd.read_csv('50_Startups.csv')

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

print(df.isnull().sum())

from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
X[:, :3] = imputer.fit_transform(X[:, :3])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

""" # 다중 선형 회귀

"""

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

#다중 선형 회귀
print(np.concatenate((y_pred.reshape(-1, 1), y_test.reshape(-1, 1)), 1))